# Generated by Django 5.0.3 on 2024-04-06 03:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_useraccess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccess',
            name='article_C',
        ),
        migrations.AddField(
            model_name='useraccess',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='useraccess',
            name='article_create',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccess',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccess',
            name='location',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccess',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
