# Generated by Django 5.0.3 on 2024-04-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_remove_useraccess_article_c_useraccess_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccess',
            name='article_delete',
            field=models.BooleanField(default=False),
        ),
    ]
