# Generated by Django 4.1.7 on 2024-04-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_useraccess_todo_access_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccess',
            name='todo_rights',
            field=models.BooleanField(default=False),
        ),
    ]
