# Generated by Django 4.1.7 on 2024-04-20 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_useraccess_todo_rights'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccess',
            name='age',
        ),
        migrations.RemoveField(
            model_name='useraccess',
            name='location',
        ),
    ]
