# Generated by Django 4.2.14 on 2024-07-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_useraccess_admin_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccess',
            name='send_email_trigger',
            field=models.BooleanField(default=False),
        ),
    ]
