# Generated by Django 5.0.3 on 2024-04-14 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap_test', '0002_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='author',
        ),
        migrations.RemoveField(
            model_name='books',
            name='user',
        ),
        migrations.DeleteModel(
            name='EmpFile',
        ),
        migrations.DeleteModel(
            name='Books',
        ),
    ]
