# Generated by Django 4.1.7 on 2024-04-16 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsample', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='user',
        ),
    ]
