# Generated by Django 5.0.3 on 2024-04-11 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_from', models.CharField(max_length=50)),
                ('email_to', models.CharField(max_length=50)),
                ('email_body', models.TextField(max_length=400)),
                ('replied', models.BooleanField(default=False)),
                ('replied_date', models.DateTimeField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailANS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_from', models.TextField(max_length=50, null=True)),
                ('email_to', models.TextField(max_length=50, null=True)),
                ('email_body', models.TextField(max_length=400)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('package_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('email_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_mail.emaildb')),
            ],
        ),
    ]
