# Generated by Django 5.0.3 on 2024-04-11 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mail', '0002_remove_emailans_email_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailans',
            name='email_from',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='emailans',
            name='email_to',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
