# Generated by Django 5.0.3 on 2024-04-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mail', '0005_alter_emailans_email_from_alter_emailans_email_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailans',
            name='email_to',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
