# Generated by Django 4.1.7 on 2024-04-17 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mail', '0010_alter_emailans_email_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailans',
            name='email_to',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
