# Generated by Django 4.2.14 on 2024-07-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mail', '0014_alter_emailans_email_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailans',
            name='email_ref_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
